allowBuilds:
  msgpackr-extract: false
minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
overrides:
  vite@*: npm:@voidzero-dev/vite-plus-core@0.2.6
  vitest@*: 4.1.10
