/** Transport-neutral package API for CLI, MCP, and other inspection adapters. */
export {
  inspectExport,
  inspectExportSignatures,
  inspectInterfaceOverview,
  inspectPlan,
} from "#typepeek/inspection/core";
export type {
  AtomicInspectionResult,
  ExportDeclarationSpace,
  ExportInspection,
  ExportInspectionRequest,
  ExportNamespaceMember,
  InspectedDeclaration,
  InspectedSignature,
  InspectionOutcome,
  InspectionPlan,
  InspectionPlanQuery,
  InspectionPlanRequest,
  InspectionResult,
  InterfaceOverview,
  InterfaceOverviewRequest,
  PackageIdentity,
  ResolutionVariant,
  SignatureInspection,
  SignatureInspectionRequest,
  SignatureBinding,
  SignatureParameter,
  SignatureReturn,
  SignatureThisParameter,
  SignatureTypeParameter,
  SignatureTypeParameterModifier,
} from "#typepeek/inspection/protocol";
