/** Transport-neutral package API for the CLI and future inspection adapters. */
export {
  comparePublicInterfaces,
  inspectExport,
  inspectExportDeclarations,
  inspectExportMember,
  inspectExportSearch,
  inspectExportSignatures,
  inspectInterfaceOverview,
  inspectPlan,
  inspectPublicSubpaths,
} from "#typepeek/inspection/core";
export {
  INSPECTION_BUDGET_DIMENSIONS,
  INSPECTION_FAILURE_REASONS,
  INSPECTION_INTENTS,
  INSPECTION_PROTOCOL_VERSION,
  inspectCapabilities,
} from "#typepeek/inspection/protocol-metadata";
export { invokeInspectionProtocol } from "#typepeek/inspection/versioned-protocol";
export type {
  AtomicInspectionResult,
  DeclarationInspection,
  DeclarationInspectionRequest,
  ExportDeclarationSpace,
  ExportInspection,
  ExportInspectionRequest,
  ExportSearch,
  ExportSearchRequest,
  ExportNamespaceMember,
  InspectedDeclaration,
  InspectedSignature,
  InspectionFailure,
  InspectionOutcome,
  InspectionProtocolRequest,
  InspectionProtocolResponse,
  InspectionProtocolResponseOptions,
  InspectionPlan,
  InspectionPlanQuery,
  InspectionPlanRequest,
  InspectionResult,
  InspectionRequestByIntent,
  InterfaceOverview,
  InterfaceOverviewRequest,
  MemberInspection,
  MemberInspectionRequest,
  PackageIdentity,
  ProtocolInspectedSignature,
  ProtocolInspectionOutcome,
  ProtocolInspectionPlan,
  ProtocolInspectionResult,
  ProtocolRecoveryGuidance,
  ProtocolRecoveryReason,
  ProtocolSignatureInspection,
  PublicSubpathDiscovery,
  PublicSubpathDiscoveryRequest,
  PublicInterfaceComparison,
  PublicInterfaceComparisonRequest,
  PublicInterfaceComparisonTarget,
  ResolutionVariant,
  SignatureInspection,
  SignatureInspectionRequest,
  SignatureBinding,
  SignatureEvidenceKind,
  SignatureEvidenceProjection,
  SignatureParameter,
  SignatureReturn,
  SignatureThisParameter,
  SignatureTypeParameter,
  SignatureTypeParameterModifier,
  StructuredInspectedSignature,
  ExactInspectedSignature,
} from "#typepeek/inspection/protocol";
export type {
  InspectionBudgetDimension,
  InspectionCapabilities,
  InspectionFailureReason,
  InspectionIntent,
  InspectionRequestDescriptor,
  InspectionRequestFieldDescriptor,
} from "#typepeek/inspection/protocol-metadata";
export { SIGNATURE_EVIDENCE_KINDS } from "#typepeek/inspection/signature-evidence-projection";
